### ISSUE TITLE
npm ERR! 404 'bookiza' is not in the npm registry

### ISSUE THREAD

**Issue by shsbd** [bookiza/bookiza#1]
npm ERR! node v4.2.1
npm ERR! npm  v3.3.9
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs

npm ERR! 404
npm ERR! 404 'bookiza' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the nam

npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:

**Comment by marvindanig** [comment]
Oh yep, I'm still working out things before it's ready for npmregistry.

**Comment by shsbd** [comment]
Thanks for your early response and suggestions.

**Comment by marvindanig** [comment]
The package is available now.
