### ISSUE TITLE
Reinstate credit for my code contributions

### ISSUE THREAD

**Issue by craigleat** [bookiza/bookiza#10]
@marvindanig you have attempted to [erase](https://github.com/bookiza/bookiza/commit/47ff341ea38ca4a73b28a0690e1c931db9d465c4) the history and with it the credits for my code contributions have disappeared. I want credit for my work reinstated.

I raised an [issue](https://github.com/bookiza/bookiza/issues/9) regarding the sources used to seed this project and you locked the conversation before I was finished. I wished to point out this [commit.](https://github.com/bookiza/bookiza/blob/019f2e9e98ced0bdeb344fbbf1e76a22d757bcc4/crust/scripts/dough.js) This code is not your own, it was likely copied from [here.](http://turnjs.com/catalog/assets/js/turn.min.js)

Follow carefully. First get the libs:

```$ wget http://turnjs.com/catalog/assets/js/turn.min.js```

```$ wget https://raw.githubusercontent.com/bookiza/bookiza/019f2e9e98ced0bdeb344fbbf1e76a22d757bcc4/crust/scripts/dough.js```

Beautify the compressed lib:

```$ js-beautify turn.min.js > turn.js```

Finally inspect the difference:

```$ diff -bBdE -I " &nbsp;   " turn.js dough.js```

```1c1 < /*! turn.js 5.0.0  24-01-2014 ~ (c) 2014 Emmanuel Garcia ~ http://turnjs.com*/ ! function(a) { --- > !function(a) {```

```2a3 >   b.isFirefoxOrIE = (typeof InstallTrigger !== 'undefined') || ( /*@cc_on!@*/ false || !!document.documentMode);```

```305a305,307 >   }, b._registerEvents = function(a) { &gt; &nbsp; &nbsp; for (var b = 0; b &lt; a.length; b++) this._registerEvent(a[b], a[b].eventName); >   }```

```$ ```

Wow! Out of +2500 lines of code diff finds three differences. You have not adapted [TurnJS V3](https://github.com/blasten/turn.js), but plagiarized a proprietary version.

**Comment by marvindanig** [comment]
This is a final warning. Stop trolling us, and stop wasting our time.

> plagiarized a proprietary version.

Plagiarized, how? We have never claimed that it is our code. For questions about Turnjs or its licensing terms please forward your questions to its creators on their site. Like we confirmed to you earlier this library was available under MIT and has switched its FOSS license back and forth many times in the past few years. 

That is all we know and you should probably take up the matter with its creator. 

When you do, we recommend you to also take up with them about your claim that some code in there has been lifted from iScroll and the slider is some distant cousin of jQuery_UI. 👍   

--- 

Regarding credits for the contributions from you, the new repo you see here is as yet *unreleased*. When the new release is out it will not contain any of your code, nor any library with questionable licensing terms. 

Until such time you're advised to strictly refrain from making any further ruckus on this repository.
