### ISSUE TITLE
Back and forward arrows on book reader view doesn't work with Chrome on Windows

### ISSUE THREAD

**Issue by brianly** [bookiza/bookiza#3]
I am able to navigate back and forward with my cursor keys.

Repro steps:

1. Go to https://bubbl.in/book/porridge-by-craig-leat
2. Try to click forward arrow to right of book.

My Chrome version: 49.0.2623.28 beta-m (64-bit)

Console: Didn't see any output.

**Comment by marvindanig** [comment]
Unable to reproduce the issue on my windows machine but heard from a few more people about it, so I presume this issue affects only a subset of windows machines with a very specific version of Chrome. 

Prima facie, it looks like a CSS issue -- the element being over-arched by something else or the height:attribute not applied correctly. If not CSS, it could also be a JS issue with `pointer-events:none;` not being unset to `auto` correctly.

Can you investigate meanwhile I'll go and find a windows machine on which I can reproduce the bug.

**Comment by crertel** [comment]
Seems to work on `Version 48.0.2564.109 m`.

Cheers!

**Comment by marvindanig** [comment]
I couldn't reproduce the issue on any of the windows machines with chrome that I've encountered. Either the bug must have died or it will pop-up again somewhere. In that situation we can re-open this issue.
